### ISSUE TITLE
Lists SDK

### ISSUE THREAD

**Issue by karlbarek** [OfficeDev/Office-365-SDK-for-iOS#40]
Has the List portion of the sdk been completed? I'm trying to get Lists working and it's not allowing me to create a ListClient object.

**Comment by dorinsimina** [comment]
Is here any example of how to use the Lists SDK because the references from http://dev.office.com/ios does not seem to be valid? ... at least the entry point and from there specific operation calls

**Comment by anihojnadel** [comment]
We started adding those samples to use as a guide. I'll let you know once they're ready (I hope to have them ready for tomorrow EOD).

**Comment by anihojnadel** [comment]
I've created a new branch with some WIP tests, you can see the code [here](https://github.com/OfficeDev/Office-365-SDK-for-ios/tree/lists-tests) (you'll need to update with your info to make them work, see BaseController -> getListClient method).

This is how you create a new list client and get the available lists:

```
OAuthentication *credentials = [[OAuthentication alloc] initWith:token];
ListClient *client = [[ListClient alloc] 
initWithUrl:@"https://yoursharepoint-my.sharepoint.com/personal/user_contoso_com" 
credentials:credentials];

[client getLists:^(NSMutableArray *lists, NSError *error) {
      //your code 
    }]
```

Let us know if this worked for you.

**Comment by dorinsimina** [comment]
Yes, it works. Thanks.

**Comment by dorinsimina** [comment]
It is possible to get access to an image resource parsed between the list items?

Using SDWebImage I tried to prepare such a request, but it returned me 403. After that I tried to set the Authorisation header and now I get 401.

<code>
    SDWebImageDownloader *manager = [SDWebImageManager sharedManager].imageDownloader;
   
    NSString *authHeader = [NSString stringWithFormat:@"Bearer %@", self.token];

    [manager setValue:authHeader forHTTPHeaderField:@"Authorization"];
</code>

**Comment by karlbarek** [comment]
In regards to the 401. We have seen that when trying to access resources such as images. For example, to open a document from SharePoint inside our mobile app it won't launch the interactive preview in an internal WebView or external browser without having the user re-authenticate . The SharePoint oAuth token created from ADAL doesn't work.

**Comment by dorinsimina** [comment]
For the moment I've created a custom Web API deployed on Azure servers which returns me the image. So from my app I'm passing to the service the image path and I get the image stream.

**Comment by karlbarek** [comment]
Dorinsimina, 
Would you be willing to share that Web API code?

**Comment by dorinsimina** [comment]
Yes, tomorrow I will post it since I still have to make some changes. Anyway I'm not a C# expert so the coding could be better I guess, but it works. The concept could be extended to get any resource not only an image (e.g. a document).

**Comment by anihojnadel** [comment]
@dorinsimina I didn't understand what you're trying to do. The auth header is handled by our SDK. Do you have more input?

**Comment by dorinsimina** [comment]
After parsing the items for a specific list I wanted to get an image resource. For example for my 'Social' list I get all the items and each item could have a picture url.

The picture URL has the following format: https://<tenant>.sharepoint.com/<path>.png

I've tried to get the image without/with setting the authorisation header but it constantly fails. On order to fix the issue I've created a custom Web Api on my azure servers to retrieve the image.

**Comment by anihojnadel** [comment]
@dorinsimina This is something we already implemented for the Android SDK, but we're still in progress for iOS. If you need that feature right now, you can take a look to the [DocLibClient](https://github.com/OfficeDev/Office-365-SDK-for-Android/blob/79c365db5eb776c8b3cb4d4c0714132bd724537d/sdk/sharepoint-services/src/main/java/com/microsoft/sharepointservices/DocLibClient.java) to see what we did for the Android platform.

**Comment by cjgehinscott** [comment]
@anihojnadel I have tried using the DocLibClient on the Android side, as I am building an app that is working with Sharepoint in Android, and I still get a 401 unauthorized.  What @dorinsimina is trying to get across is that the access token that is being passed in the authorization header is not being accepted hence the 401.  It has nothing to do with the implementation on the client/application side; if it was a bad request we wouldn't get a 401 we would get something in 500s.  This is why @dorinsimina, I'm assuming, built a web service that can access those resources to pass down to the app/client that can't access them.  My guess is that there is something on the back end with those resources needing to be set up to accept an access token that is created in Azure for a mobile application.

**Comment by ravidixit** [comment]
@anihojnadel  I was looking for List implementation for iOS and came across this thread, got some valuable inputs and tried your WIP test implementation using the ADAL token which we get when we login but am not able to get any response.

Can you help us in resolving this with an example something similar to the one in example folder or some resource online which could guide us out.

**Comment by dorinsimina** [comment]
You can use the following sample:

<code>
OAuthentication *credentials = [[OAuthentication alloc] initWith:token];
ListClient *clientList = [[ListClient alloc] initWithUrl:@"https://TENANT-my.sharepoint.com/personal/USER/" credentials:credentials];
    
 clientList getLists:^(NSMutableArray *lists, NSError *error) ...
</code>

**Comment by ravidixit** [comment]
@dorinsimina  : what's the token variable here is it the same one which we get when we login or something else?

**Comment by dorinsimina** [comment]
The token variable is the one obtained by granting access to the resource https://TENANT-my.sharepoint.com

**Comment by ravidixit** [comment]
@dorinsimina  Here's the code that i am trying 

    NSString *appToken = [[NSUserDefaults standardUserDefaults] valueForKey:@"loginToken"];
    NSString* hostName = @"https://TENANT-my.sharepoint.com/personal/USER";
    
    OAuthentication *credentials = [[OAuthentication alloc] initWith:appToken];
    ListClient *client = [[ListClient alloc]
                          initWithUrl:hostName
                          credentials:credentials];
    
    NSURLSessionTask* task =  [client getLists:^(NSMutableArray *lists, NSError *error) {
        if (error==nil) {
            NSLog(@"%@",lists);
        }
    }];
    
    [task resume];

The lists array is always empty, I even replaced the USER with my name but still it's empty. I am trying to fetch the announcements list and few custom list from the tenant not sure where I am wrong.

**Comment by dorinsimina** [comment]
For example if the tenant is 'test' and the user is 'john.doe@test.onmicrosoft.com' the resource link could be the following:
https://test-my.sharepoint.com/personal/john_doe_test_onmicrosoft_com/

Also make sure that your Office 365 native application has granted the access for SharePoint online files access.

**Comment by ravidixit** [comment]
@dorinsimina : did what you suggested but still no luck maybe my token is wrong, I am passing the token as the one which I get after login. 

I have tested the same code in the browser in the browser it works since I am already logged in with my credentials, also i have checked the Office 365 sharepoint online permissions i have full control to all site collection.

I have opened up a issue on a new thread where i have detailed on what i am doing maybe you guys can help me out on that

https://github.com/OfficeDev/Office-365-SDK-for-iOS/issues/52

**Comment by ZuzooVn** [comment]
```
initWithUrl:@"https://yoursharepoint-my.sharepoint.com/personal/user_contoso_com" 
credentials:credentials];
```

How can I automatically get this link for each account without hardcode data?

Thanks

**Comment by anihojnadel** [comment]
@ZuzooVn  You can do that by using the Directory SDK.

https://github.com/OfficeDev/Office-365-SDK-for-iOS/issues/86#issuecomment-140737454
